version: '3.8'

services:
  mongo:
    container_name: mongodb
    image: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./database:/test_tasks/database

  tasks:
    container_name: tasks
    build: .
    command: python test_tasks.py
    volumes:
      - .:/test_tasks
    depends_on:
      - mongo


volumes:
  database: