version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 8081:8081
    volumes:
      - ./database:/test_tasks/database

  tasks:
    container_name: tasks
    build: .
    command: python test_tasks.py
    restart: always
    volumes:
      - .:/test_tasks
    depends_on:
      - mongo


volumes:
  database: